### ISSUE TITLE
WinGet manifest for Windows

### ISSUE THREAD

**Issue by adigitoleo** [thonny/thonny#2322]
WinGet is an official command line package manager for Windows 11 (I think it's also available for some Win10 editions). I wonder if there is interest in registering an WinGet build manifest. Since there is already an installer for Windows, this is quite simple, but I wonder how  it is best to integrate with the release cycle. On PowerShell, I used the "wingetcreate" executable as per the [winget manifest docs]https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example) to come up with the following:

`Thonny.Thonny.locale.en-US.yaml`:

```
# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Thonny.Thonny
PackageVersion: 3.3.14
PackageLocale: en-US
Publisher: Thonny
PublisherUrl: https://github.com/thonny
Author: Aivar Annamaa
PackageName: Thonny
PackageUrl: https://thonny.org/
License: MIT License
LicenseUrl: https://github.com/thonny/thonny/blob/master/LICENSE.txt
Copyright: Copyright (c) 2022 Aivar Annamaa
ShortDescription: Python IDE for beginners
Tags:
- Python
- IDE
ReleaseNotes: https://github.com/thonny/thonny/releases/tag/v3.3.14
ReleaseNotesUrl: https://github.com/thonny/thonny/releases/tag/v3.3.14
ManifestType: defaultLocale
ManifestVersion: 1.1.0
```

`Thonny.Thonny.installer.yaml`

```
# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Thonny.Thonny
PackageVersion: 3.3.14
Installers:
- Architecture: neutral
  InstallerType: inno
  InstallerUrl: https://github.com/thonny/thonny/releases/download/v3.3.13/thonny-3.3.13.exe
  InstallerSha256: 3E95738C44F95835DFBECC4BABDFBFA4E86E75EA4FC4F6B127FDE329EE4BD458
ManifestType: installer
ManifestVersion: 1.1.0
```

`Thonny.Thonny.yaml`:

```
# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: Thonny.Thonny
PackageVersion: 3.3.14
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0
```

To test, put these in a folder and use `winget -m <folder_name>`. Note, it is necessary to use the folder name not the path to the manifest file (https://github.com/microsoft/winget-cli/issues/1064)

So, either the `wingetcreate` tool could be used to create these at each release (in CI?), or  some template based on the above could be used, with some kind of bat file to increment the version. Anyway, not a priority issue but just some ideas.
